4MiB Partition for firmware
* 4Mib partition size for firmware
* Precalculate RPM table
* Fix wi-fi error on start with non-exist SSID name
* fix release tagging
* Bump version to v0.5

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,48 +13,74 @@ jobs:
   build:
     runs-on: self-hosted
     steps:
+      # Checkout the repository
+      - name: Checkout builder
+        uses: actions/checkout@v2
 
+      # Get the current date
       - name: Get current date
         id: date
         run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
 
-      #- name: mount ramfs of build
-      #  run: sudo /usr/local/bin/mount_ramfs.sh
-
-      - name: Checkout builder
-        uses: actions/checkout@v1
-
+      # Install the ARM toolchain
       - name: Install arm toolchain
         run: ./scripts/install_arm.sh
 
-      - name: Install ESP-IDF toolchain
-        run: ./scripts/install_espidf.sh
+      # Install the ESP-IDF toolchain
+      - name: Conditionally Install ESP-IDF Toolchain
+        run: |
+          set +e  # Disable immediate exit on error to allow conditional logic
+          source esp-idf/export.sh
+          EXPORT_RESULT=$?
+          set -e  # Re-enable immediate exit on error for subsequent commands
+          if [ $EXPORT_RESULT -ne 0 ]; then
+            echo "Sourcing esp-idf/export.sh failed. Installing ESP-IDF toolchain..."
+            ./scripts/install_espidf.sh
+          else
+            echo "esp-idf/export.sh sourced successfully."
+          fi
 
+      # Checkout necessary submodules or projects
       - name: Checkout ulab/micropython
         run: ./scripts/init.sh
 
+      # Create a directory for artifacts
       - name: Create artifacts directory
-        run: mkdir ./artifacts
+        run: |
+          rm -rf ./artifacts
+          mkdir ./artifacts
 
+      # Ensure all relevant scripts are executable
       - name: Give execution permissions
-        if: always()
         run: chmod +x ./scripts/esp32/generic-s3-spiram-16mb-ota.sh
 
+      # Check the hostname and set environment variables accordingly
       - name: Check hostname and set MAKEOPTS
         run: |
           if [ "$(hostname)" = "reefpi" ]; then
-            echo "MAKEOPTS=2" >> $GITHUB_ENV
+            echo "MAKEOPTS=-j2" >> $GITHUB_ENV
           fi
-        if: always()
 
+      # Compile the project for ESP32-S3 with specific configuration
       - name: Compile for ESP32-S3 8MB SPIRAM/16MB Flash
-        if: always()
         run: ./scripts/esp32/generic-s3-spiram-16mb-ota.sh
 
-      - uses: "marvinpinto/action-automatic-releases@latest"
+      # Extract the branch name and set a dynamic tag for the build
+      - name: Extract Branch Name and Set Tag
+        if: github.event_name == 'push'
+        run: |
+          BRANCH_NAME=${GITHUB_REF#refs/heads/}
+          DATE=$(date +'%Y%m%d')
+          SHORT_SHA=$(git rev-parse --short HEAD)
+          echo "RELEASE_TAG=${BRANCH_NAME}-${DATE}-${SHORT_SHA}" >> $GITHUB_ENV
+
+      # Create a GitHub release with the artifacts
+      - name: Create GitHub Release
+        uses: marvinpinto/action-automatic-releases@latest
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           prerelease: false
-          automatic_release_tag: "latest"
-          title: "Release date ${{ steps.date.outputs.date }}"
+          automatic_release_tag: "${{ env.RELEASE_TAG }}"
+          title: "Release ${{ env.RELEASE_TAG }}"
           files: ./artifacts/*
+        if: env.RELEASE_TAG != ''
